### ISSUE TITLE
Easy-Ipm

### ISSUE THREAD

**Issue by nolovenolife** [MaybeShewill-CV/Easy-Ipm-Client#10]
请问这个libeasy_ipm_model库开源了吗？

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 没有

**Comment by ffddlihong** [comment]
您好，请问是否可以根据相机内外参数矩阵直接生成remap矩阵。

**Comment by nolovenolife** [comment]
![image](https://user-images.githubusercontent.com/10968289/81935503-4ee6ed00-9623-11ea-80bb-4ad5815eb352.png)
请教下remap.yml就是由这个公式计算出来的是吧？还有就是tusimple数据集的摄像机的pitch角您是如何获取到的？
非常感谢~

**Comment by MaybeShewill-CV** [comment]
@ffddlihong pitch角度是模拟的:)

**Comment by ffddlihong** [comment]
> @ffddlihong pitch角度是模拟的:remap.yml的生成代码方便发我学习下吗？感谢

**Comment by nolovenolife** [comment]
我在尝试通过上面的公式生成我自己的图片的remap.yml，但是还没搞出来。这部分代码您方便发我看学习下吗?ffddlihong@163.com   感谢~

**Comment by nolovenolife** [comment]
这个项目计算remap.yml文件的入参好像和论文里面的不一样。论文里面是不需要灭点的，但是这里需要。

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 不完全和论文上的一样 这部分代码不能提供哈：）

**Comment by nolovenolife** [comment]
好的  谢谢您。对于刚接触这一领域的新人，您的项目对我帮助很大。

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 不客气:)

**Comment by nolovenolife** [comment]
![image](https://user-images.githubusercontent.com/10968289/82026546-74c4ce00-96c5-11ea-87f0-4b7f0a640299.png)
请问这个接口返回错误了怎么排查？可能是什么问题？

**Comment by MaybeShewill-CV** [comment]
@ffddlihong Debug编译下 调试吧 看这个看不出来什么问题

**Comment by nolovenolife** [comment]
这个接口调试不进去。ipm_model是库的形式提供的。没办法进去。我使用的camera_calib.yml格式是
![image](https://user-images.githubusercontent.com/10968289/82028275-ff0e3180-96c7-11ea-92be-c2155fa33074.png)
不知道对不对

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 标准的opencv yml文件格式就可以了.

**Comment by nolovenolife** [comment]
看代码里面只用填相机内参和畸变参数就可以是吧

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 需要在gui上填灭视点坐标和模拟的pitch角度

**Comment by nolovenolife** [comment]
都填了的。参照您image目录下的ipm_param_example_2.png填的

**Comment by nolovenolife** [comment]
注意到test_data里面有实例yml，按这个来可以了。

**Comment by MaybeShewill-CV** [comment]
@ffddlihong ok

**Comment by nolovenolife** [comment]
还想请教下，基于灭点的方式能得出俯视图。但是如何获取转换矩阵并且将转换矩阵转成remap文件？我这边看到的论文基于灭点都是双层for循环去转换坐标的。对应就是adaptiveIpmModel.h里面的create_remap接口，谢谢~

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 也是通过双层循环计算坐标的对应关系的:)

**Comment by nolovenolife** [comment]
好的，谢谢。我主要是想请教下，您在create_remap接口里面如何生成您在lanenet_detection中使用的tusimple_remap.yml文件

**Comment by ffddlihong** [comment]
好的，谢谢。我主要是想请教下，您在create_remap接口里面如何生成您在lanenet_detection中使用的tusimple_remap.yml文件

**Comment by nolovenolife** [comment]
如果是四点法，您是如何选的点呢？

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 你想直接通过调用create_remap方法来生成remap矩阵是不能生成的。这部分接口我没有开放. 灭视点靠经验手选的:)

**Comment by nolovenolife** [comment]
好的，感谢。能大概说下生成remap矩阵的思路吗？

**Comment by MaybeShewill-CV** [comment]
@ffddlihong remap就是计算新生成的图上的坐标对应原图的坐标点 你实现了坐标转换 每个点转换一下就好了:)
