### ISSUE TITLE
how to invert to origin image 

### ISSUE THREAD

**Issue by qixuxiang** [MaybeShewill-CV/Easy-Ipm-Client#2]
Hi, thanks for your awesome code share!
I wonder if I can invert to origin image  after IPM operation, that is, if I detect a object(such as a car) in bird view map, how can I label it to origin image.

Looking for you replies and thanks a lot!

**Comment by MaybeShewill-CV** [comment]
Every pixel on the ipm image has its corresponding pixel on the origin image:)





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by northeastsquare** [comment]
IPM图片标注的俯视图里面的car, 对应的像素是地面坐标，那么转换回原始图片，应该是车辆下底边的四个点，而不是原图里面车辆的矩形
