### ISSUE TITLE
Need some help, thanks

### ISSUE THREAD

**Issue by sygin123** [MaybeShewill-CV/Easy-Ipm-Client#3]
Thanks for sharing your amazing work! I have two question:
1) Can you share your method about how to calibrate pitch, yaw, roll angle and vanish point?
2) Would you like to open source the adaptiveImpModel.cpp ?

**Comment by MaybeShewill-CV** [comment]
@sygin123 1.You may select your vanish point by yourself on the image. 2.Sorry I can not offer you the details about calibration process but it's almost the same as the way used in apollo or autoware, you may check their calibration module. 3. I will not release the adaptiveIpmModel.cpp source code for now 4.By the way the accurate pitch angle is not necessary for the model you may adjust the pitch angle and the vanish point to obtain the ipm image which you're satisfied with :)

**Comment by sygin123** [comment]
OK, I will check it out, thanks. For another, the final equation in the paper ''Adaptive Inverse Perspective Mapping for Lane Map Generation with SLAM", we can see the FOV is needed. However, your tool does not input this information, do you deduce it from the intrinsic matrix and how? 
By the way, I am confused about how to use the vanishing point. Do you use it to get maximum range for IPM image?
It would be appreciated for share the algorithm in ipm_tranform!

**Comment by MaybeShewill-CV** [comment]
@sygin123 1.The vanish point is used to select the roi of source image which will be transformed into ipm image. 2.FOV information was hard coded into the model, if your test result is bad due to the fov information, I will make it optional in the ui interface:)

**Comment by sygin123** [comment]
@MaybeShewill-CV It will be great if the tool can set FOV in the ui interface. Thanks again. ^_^

**Comment by ElPatou** [comment]
How are we supposed to compile the project if some codes are missing (i.e. adaptiveIpmModel.cpp)?

**Comment by MaybeShewill-CV** [comment]
@ElPatou I just not open source the source code to you. ==!
