### ISSUE TITLE
lanenet_lane_detection  .yml

### ISSUE THREAD

**Issue by zhangtiantian12311** [MaybeShewill-CV/Easy-Ipm-Client#4]
can you tell me that how to generate tusimple_ipm_remap.yml on my data,thank you very much
![image](https://user-images.githubusercontent.com/43676340/60093945-4b354800-977d-11e9-8be4-ba316f06294c.png)
.txt????

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 This repo was not able to generate the remap yml file which was used in lanenet detection directly. But you can modified the project to get it. The remap file used in the lanenet detection share the same algorithm:)

**Comment by zhangtiantian12311** [comment]
------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上7:57
收件人: "MaybeShewill-CV/Easy-Ipm-Client"<Easy-Ipm-Client@noreply.github.com>;
抄送: "zhangtiantian12311"<313076283@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MaybeShewill-CV/Easy-Ipm-Client] lanenet_lane_detection  .yml(#4)



@zhangtiantian12311 This repo was not able to generate the remap yml file which was used in lanenet detection directly. But you can modified the project to get it. The remap file used in the lanenet detection share the same algorithm:)
 
&mdash;
