### ISSUE TITLE
lanenet_detection

### ISSUE THREAD

**Issue by zhangtiantian12311** [MaybeShewill-CV/Easy-Ipm-Client#5]
![image](https://user-images.githubusercontent.com/43676340/60094097-b2eb9300-977d-11e9-9744-29ac4220f9fd.png)
i have generate above .yml,but it not i wanted in lanenet_detection

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 You can not get the remap yml via this project. You may have to modified this project yourself to get the remap yml file:)
