### ISSUE TITLE
Questions for IPM stitching

### ISSUE THREAD

**Issue by dehong8733** [MaybeShewill-CV/Easy-Ipm-Client#7]
Thanks for sharing your amazing work!
Hello, i'm interested in the method about how you stitch those IPM images with geographic coordinates. 
Would you like to share some references or open source?
Thank you very much

**Comment by MaybeShewill-CV** [comment]
@dehong8733 That's not part of my work so i won't make it open source:)

**Comment by dehong8733** [comment]
Oh I see!  Thanks
