### ISSUE TITLE
undefined reference to `QString::toUtf8_helper(QString const&)@Qt_5'

### ISSUE THREAD

**Issue by ElonKou** [MaybeShewill-CV/Easy-Ipm-Client#8]
Thanks for your great work, I found that there are some errors when I compile the project. 
Could you please tell me the version of qt, I'm using qt5.0 now, thank you very much.
```
# commmand
qmake -spec linux-g++ -o Makefile ../src/easy_ipm_client.pro
# errors
/home/maxsense/PYTHON/18.IPM_project/Easy-Ipm-Client/src/../easy_ipm_lib/release/libeasy_ipm_model.so: undefined reference to `QString::toUtf8_helper(QString const&)@Qt_5'

```

**Comment by MaybeShewill-CV** [comment]
@ElonKou I'll check it tomorrow. Off work now:)

**Comment by ElonKou** [comment]
thank you very much,I have solved it by change the qmake path.
My default qmake path is belong to Qt5.5.

**Comment by MaybeShewill-CV** [comment]
@ElonKou Welcome:)
